### ISSUE TITLE
403 Invalid CSRF token when running locally

### ISSUE THREAD

**Issue by huksley** [darekkay/todoist-export#20]
Seems like API changed see https://developer.todoist.com/sync/v9/
`All Sync API requests share the same endpoint URL: https://api.todoist.com/sync/v9/sync`

Additionally  OAuth not working for me.
Workaround is to create a token on the Settings page and to use it in the callApi method as a header.

Error I get if trying to use OAuth on sync method:

```
data: {
      error: 'Invalid CSRF token',
      error_code: 410,
      error_extra: [Object],
      error_tag: 'AUTH_INVALID_CSRF_TOKEN',
      http_code: 403
    }
```

**Comment by tkedwards** [comment]
I also get a 403 response when running locally:

```
Request failed with status code 403

Error: Request failed with status code 403
    at createError (/home/tim/bin/todoist-export/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/tim/bin/todoist-export/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/tim/bin/todoist-export/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I assume Todoist have given us an early 'Christmas present' with another API change?

**Comment by huksley** [comment]
I made a fix, could you try @tkedwards ?

**Comment by tkedwards** [comment]
@huksley  Works great, thanks very much!
